#pragma once
#ifndef _JOYSTICKMAPPING_
#define _JOYSTICKMAPPING_

#define JOY_BUTTON_UP 1
#define JOY_BUTTON_DOWN 2
#define JOY_BUTTON_RIGHT 10
#define JOY_BUTTON_LEFT 11

#endif // !_JOYSTICKMAPPING_
